# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqJvV7PadQ73wj-HBgiQaXewrrum2X9_
"""

import numpy as np
import matplotlib.pyplot as plt

# 🌱 Soil column parameters
depth = 1.0           # depth of soil column in meters
nz = 100              # number of vertical points
dz = depth / nz       # vertical resolution
dt = 0.01             # time step in seconds
nt = 1000             # number of time steps

# 🧪 Physics parameters
D = 0.001             # diffusion coefficient (m^2/s)
E = 0.0001            # evaporation rate at surface (1/s)

# 📊 Initialize soil moisture profile
theta = np.zeros(nz)         # initial moisture = 0 everywhere
theta[0:10] = 1.0            # top 10 layers are saturated (initial irrigation)

# ⏱️ Time loop
history = []
for t in range(nt):
    theta_new = theta.copy()
    for i in range(1, nz-1):
        diffusion = D * (theta[i+1] - 2*theta[i] + theta[i-1]) / dz**2
        theta_new[i] += dt * diffusion

    # Surface evaporation
    theta_new[0] -= dt * E

    # No-flux bottom boundary
    theta_new[-1] = theta_new[-2]

    theta = theta_new.copy()

    # Save profile every 100 steps
    if t % 100 == 0:
        history.append(theta.copy())

# 🎨 Plot moisture profiles at selected times
plt.figure(figsize=(6, 5))
for i, profile in enumerate(history):
    plt.plot(profile, np.linspace(0, depth, nz), label=f't = {i*dt*100:.1f}s')
plt.gca().invert_yaxis()
plt.xlabel('Soil Moisture (θ)')
plt.ylabel('Depth (m)')
plt.title('Soil Moisture Evolution Over Time')
plt.legend()
plt.grid(True)
plt.savefig("moisture_evolution.png", dpi=300)
plt.show()

# 📡 Simulate IoT Sensor Readings with Noise
def add_sensor_noise(data, noise_std=0.02):
    noisy = data + np.random.normal(0, noise_std, size=data.shape)
    return np.clip(noisy, 0, 1)  # keep between 0 and 1

# Final profile as "true data"
true_profile = theta.copy()
sensor_profile = add_sensor_noise(true_profile)

# 🖼️ Plot True vs Sensor Moisture
plt.figure(figsize=(6, 5))
plt.plot(true_profile, np.linspace(0, depth, nz), label="True Moisture", lw=2)
plt.plot(sensor_profile, np.linspace(0, depth, nz), label="Sensor Output", lw=2, linestyle='--')
plt.gca().invert_yaxis()
plt.xlabel('Soil Moisture (θ)')
plt.ylabel('Depth (m)')
plt.title('Simulated IoT Sensor vs Ground Truth')
plt.legend()
plt.grid(True)
plt.savefig("sensor_vs_true.png", dpi=300)
plt.show()

from google.colab import files
files.download("moisture_evolution.png")
files.download("sensor_vs_true.png")